<a href="https://colab.research.google.com/github/Deeksha1-web/Deeksha-S/blob/master/Classification_Comparison_red_wine_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
dataset = pd.read_csv('/winequality-red.csv')

In [12]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [13]:
X = dataset.iloc[: , 1:-1].values
y = dataset.iloc[:, -1].values

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X ,y, test_size=0.20)

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
sc = StandardScaler()

In [18]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [20]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel= 'rbf')

In [21]:
l_cla.fit(X_train, y_train)
k_cla.fit(X_train, y_train)
d_cla.fit(X_train, y_train)
r_cla.fit(X_train, y_train)
s_cla.fit(X_train, y_train)
ks_cla.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [22]:
l_pred = l_cla.predict(X_test)
k_pred = k_cla.predict(X_test)
d_pred = d_cla.predict(X_test)
r_pred = r_cla.predict(X_test)
s_pred = s_cla.predict(X_test)
ks_pred = ks_cla.predict(X_test)

In [23]:
from sklearn.metrics import confusion_matrix

In [24]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [25]:
l_c

array([[  0,   0,   2,   0,   0,   0],
       [  0,   1,   5,   2,   0,   0],
       [  0,   2, 103,  32,   2,   0],
       [  0,   0,  42,  78,  11,   0],
       [  0,   0,   3,  17,  13,   0],
       [  0,   0,   0,   4,   3,   0]])

In [26]:
k_c

array([[ 0,  0,  1,  1,  0,  0],
       [ 0,  1,  5,  2,  0,  0],
       [ 0,  3, 91, 41,  4,  0],
       [ 0,  1, 32, 89,  9,  0],
       [ 0,  0,  9, 14, 10,  0],
       [ 0,  0,  1,  2,  4,  0]])

In [27]:
d_c

array([[ 0,  1,  1,  0,  0,  0],
       [ 0,  1,  4,  3,  0,  0],
       [ 0,  5, 92, 34,  8,  0],
       [ 0,  3, 23, 89, 14,  2],
       [ 0,  1,  4,  9, 18,  1],
       [ 0,  0,  1,  2,  2,  2]])

In [28]:
r_c

array([[  0,   0,   1,   1,   0,   0],
       [  0,   0,   7,   1,   0,   0],
       [  0,   1, 106,  30,   2,   0],
       [  0,   0,  21,  98,  12,   0],
       [  0,   0,   3,  10,  20,   0],
       [  0,   0,   0,   2,   4,   1]])

In [29]:
s_c

array([[  0,   0,   2,   0,   0,   0],
       [  0,   0,   6,   2,   0,   0],
       [  0,   0, 105,  34,   0,   0],
       [  0,   0,  42,  89,   0,   0],
       [  0,   0,   5,  28,   0,   0],
       [  0,   0,   0,   7,   0,   0]])

In [30]:
ks_c

array([[  0,   0,   1,   1,   0,   0],
       [  0,   0,   8,   0,   0,   0],
       [  0,   0, 107,  32,   0,   0],
       [  0,   0,  38,  87,   6,   0],
       [  0,   0,   5,  18,  10,   0],
       [  0,   0,   0,   5,   2,   0]])

In [31]:
from sklearn.metrics import accuracy_score

In [32]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [33]:
print('Logistic Regression: ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(l_a))

Logistic Regression: 0.609375
KNN: 0.596875
Decision Tree: 0.63125
Random Forest: 0.703125
Linear SVC: 0.60625
Kernel SVC: 0.609375


consolation : since ramdom forest accuracy is high we are considering this thank you 